import '@shared/styles/global.scss'

import { FilterYachtComponent } from '@features/filter-yacht'
import { RegistrationMobileComponent } from '@features/registration'
import { HeroComponent } from '@widgets/layout/hero'
import { ShipListComponent } from '@widgets/ship-list'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
//   return {
//     props: {
//       ...(await serverSideTranslations(locale ?? 'ru')),
//     },
//   }
// }

export default function RootLayout() {
  return (
    <div className={'w-full'}>
      <HeroComponent />
      <RegistrationMobileComponent />
      <section className={'px-page-mobile lg:grid lg:grid-cols-4 lg:px-page'}>
        <FilterYachtComponent />
        <ShipListComponent />
      </section>
    </div>
  )
}
